Level: Mid
Skills: Python, SQL, PyTorch, Docker, K3S, SQL, Deep Learning, LLM, Machine Learning, Data Analysis, A\B Test, Flask API
Experience: Obejct Detection, Image Instance Segmentation, Genetic Algorithm, Design A\B Test for experiment, Image classifcation, Recommendation system, LoRa, RAG
Fields: Panel, Intelligence Agriculture, Chemstry, Experiment
Task: Design the algorithm for the experiment to reduce test substance 40x, Design defect detection with anomaly detection and image process   
Other: Craving for knowledge, Flexibility



 

 
 